### ISSUE TITLE
Do you want to extend PyPDF2 directly? 

### ISSUE THREAD

**Issue by MartinThoma** [GRV96/PyPDF2_Fields#12]
Hello!

I've just found your package - very cool that you approached the problem that PyPDF2 does not deal well with forms / fields!

We have several open issues regarding forms. Being the new maintainer, I want to fix them. But I'm not knowledgeable enough to do it directly. I need the help of skilled people like you :-)

Do you want to write a PR to improve one aspect of forms in PyPDF2? (better do it in several smaller PRs, that makes it easier to review... In case you want/have the time to support at all)

**Comment by GRV96** [comment]
Your offer honors me. Yet, I currently cannot afford to become a PyPDF2 maintainer. Sorry.

**Comment by MartinThoma** [comment]
PRs are always welcome and way less work than becoming a maintainer 😊🤗
